### ISSUE TITLE
bug: august sveltekit breaking `routes` and `load` changes

### ISSUE THREAD

**Issue by ryanrussell** [vercel/sveltekit-commerce#19]
Opening an issue around the breaking changes in the latest version of SvelteKit. 

- `index.svelte` -> `+page.svelte` 
- Eliminate `context="module"`
- `+server.js` for backend
- etc...

Is there already an advocate at Vercel taking on these template updates? Or is the intent for the community to maintain breaking changes moving forward?

Thanks for any guidance!

**Comment by leerob** [comment]
Hey! Thanks for putting this together. We're open to community contributions 😄

**Comment by ryanrussell** [comment]
> Hey! Thanks for putting this together. We're open to community contributions smile

Doing the same upgrade for some of my own projects right now.

If someone else gets to this first, Ben McCann put together a roadmap on upgrading here: https://github.com/sveltejs/realworld/pull/123

If this hasn't been done by the time I get some extra cycles, will send a PR to bring this demo to functional on the @latest build...

**Comment by leerob** [comment]
Starting here, not ready yet though https://github.com/vercel/sveltekit-commerce/pull/20

**Comment by leerob** [comment]
This has been released!
